const KEY='catering-egypt-app-v2';
const defaults={report:{client:'Nagwa Technology',contact:'Ms. Marwa Technology',date:'23 أغسطس 2026',time:'2:00 PM - 3:10 PM',ref:'1022 / 26',proposal:'Proposed Integrated Food Services Framework',summary:'نقدر بشكل كبير التعاون والتواصل أثناء الزيارة الميدانية. يلخص هذا التقرير التقييم الشامل للعمليات الحالية ويحدد فرص تحسين جودة الخدمة والكفاءة التشغيلية والتجربة العامة.',conclusion:'في Catering Egypt، نقدم خدمات غذائية متكاملة تدعم أداء مؤسستك وتتوافق مع أعلى معايير الجودة والسلامة والتميز التشغيلي.'},quote:{client:'نجوى تكنولوجي',number:'1204 / 2026',date:'23 / 08 / 2026',notes:'الأسعار بالجنيه المصري، وتُراجع عند تغير عدد الأفراد أو نطاق الخدمة وفق العقد.'},items:[['01','وجبة الفطار الشرقي الكاملة','وجبة كاملة',65],['02','وجبة الفطار الفالحي','فطار فلاحي',85],['03','السندوتش العادي','اختيارات متنوعة',40],['04','Premium System','وجبة ساخنة وتسليم منظم',130]],design:{primary:'#0B1F3A',gold:'#C8A45D',paper:'#FAF9F5',url:'',notify:true}};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(defaults);
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function toast(msg){if(state.design.notify){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}}
function bindForm(form, target){const fd=new FormData(form); for(const [k,v] of fd) target[k]=v;}
function renderReport(){const f=$('#reportForm'); Object.entries(state.report).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v}); $$('[data-bind]').forEach(e=>{const k=e.dataset.bind;e.textContent=state.report[k]??''});}
function renderItems(){const box=$('#itemsEditor');box.innerHTML='';state.items.forEach((it,i)=>{const row=document.createElement('div');row.className='item-edit';row.innerHTML=`<input data-i="${i}" data-k="0" value="${esc(it[0])}" aria-label="رقم"><input data-i="${i}" data-k="1" value="${esc(it[1])}" aria-label="البند"><input data-i="${i}" data-k="2" value="${esc(it[2])}" aria-label="الوصف"><input data-i="${i}" data-k="3" type="number" min="0" value="${it[3]}" aria-label="السعر"><button type="button" data-remove="${i}" class="icon-btn">×</button>`;box.appendChild(row)});}
function esc(v){return String(v).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[m]))}
function renderQuote(){const f=$('#quoteForm');Object.entries(state.quote).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});$$('[data-qbind]').forEach(e=>e.textContent=state.quote[e.dataset.qbind]??'');$('#quoteRows').innerHTML=state.items.map((it,i)=>`<tr><td>${esc(it[0])}</td><td>${esc(it[1])}</td><td>${esc(it[2])}</td><td>${Number(it[3]||0).toLocaleString('en-US')}</td></tr>`).join('');$('#quoteTotal').textContent=state.items.reduce((a,x)=>a+Number(x[3]||0),0).toLocaleString('en-US');renderItems()}
function renderDesign(){document.documentElement.style.setProperty('--primary',state.design.primary);document.documentElement.style.setProperty('--gold',state.design.gold);document.documentElement.style.setProperty('--paper',state.design.paper);$('#primaryColor').value=state.design.primary;$('#goldColor').value=state.design.gold;$('#paperColor').value=state.design.paper;$('#designUrl').value=state.design.url;$('#notifyToggle').checked=state.design.notify}
function save(){localStorage.setItem(KEY,JSON.stringify(state));toast('تم حفظ البيانات على هذا الجهاز');}
async function pdf(id,name){const el=$(id); if(!window.html2canvas||!window.jspdf){toast('تعذر تحميل محرك PDF — تحقق من الاتصال');return} toast('جارٍ تجهيز PDF...'); const canvas=await html2canvas(el,{scale:2,useCORS:true,backgroundColor:'#fff',logging:false});const {jsPDF}=window.jspdf;const pdf=new jsPDF('p','mm','a4');const pageW=210,pageH=297;const img=canvas.toDataURL('image/jpeg',0.98);const ratio=Math.min(pageW/canvas.width,pageH/canvas.height);const w=canvas.width*ratio,h=canvas.height*ratio;pdf.addImage(img,'JPEG',(pageW-w)/2,10,w,h);pdf.save(name);toast('تم إنشاء ملف PDF بنجاح')}
function printEl(id){const html=$(id).outerHTML;const w=window.open('','_blank');w.document.write(`<html dir="rtl"><head><title>Catering Egypt</title><link rel="stylesheet" href="styles.css"><style>@media print{body{background:#fff}.paper{box-shadow:none;margin:0;max-width:none}}</style></head><body>${html}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),500)}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
$$('[data-go]').forEach(b=>b.onclick=()=>document.querySelector(`[data-tab="${b.dataset.go}"]`).click());
$('#reportForm').addEventListener('input',()=>{bindForm($('#reportForm'),state.report);renderReport()});$('#quoteForm').addEventListener('input',()=>{bindForm($('#quoteForm'),state.quote);renderQuote()});
$('#itemsEditor').addEventListener('input',e=>{const t=e.target;if(t.dataset.i!==undefined){state.items[+t.dataset.i][+t.dataset.k]=+t.dataset.k===3?Number(t.value):t.value;renderQuote()}});$('#itemsEditor').addEventListener('click',e=>{if(e.target.dataset.remove!==undefined){state.items.splice(+e.target.dataset.remove,1);renderQuote();save()}});
$('#addItem').onclick=()=>{state.items.push([String(state.items.length+1).padStart(2,'0'),'بند جديد','الوصف',0]);renderQuote()};$('#saveBtn').onclick=save;$('#reportPdf').onclick=()=>pdf('#reportPreview','Catering-Egypt-Report.pdf');$('#quotePdf').onclick=()=>pdf('#quotePreview','Catering-Egypt-Quotation.pdf');$('#reportPrint').onclick=()=>printEl('#reportPreview');$('#quotePrint').onclick=()=>printEl('#quotePreview');
['primaryColor','goldColor','paperColor'].forEach((id,i)=>$('#'+id).oninput=e=>{state.design[['primary','gold','paper'][i]]=e.target.value;renderDesign()});$('#designUrl').oninput=e=>state.design.url=e.target.value;$('#notifyToggle').onchange=e=>state.design.notify=e.target.checked;$('#openDesign').onclick=()=>{if(/^https?:\/\//i.test(state.design.url))window.open(state.design.url,'_blank','noopener');else toast('ضع رابط Canva أو مصدر التصميم أولاً')};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
renderReport();renderQuote();renderDesign();
